### ISSUE TITLE
Install error on MacOS Sonoma

### ISSUE THREAD

**Issue by SunflowerFuture** [simjanos-dev/LinguaCafe#225]
Hello,

When running the "chmod -R 777 ./ && docker compose up -d" command, I get the following error:

WARN[0000] /Users/***/linguacafe/docker-compose.yml: `version` is obsolete 
[+] Pulling 1/3 on
 ✘ mysql Error        context canceled                                     1.0s 
 ⠏ webserver [⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀] Pulling                              1.0s 
 ⠏ python Pulling                                                          1.0s 
no matching manifest for linux/arm64/v8 in the manifest list entries

I followed the install instructions but know very little about the tech. What could have gone wrong?
Thanks.

**Comment by simjanos-dev** [comment]
Hi! 

Do you have M1/M2/M3 processor? If so, you will need to create a .env file, and add this line to it:
```
PLATFORM="linux/amd64"
```

Then run the command again.

**Comment by SunflowerFuture** [comment]
Yes, M1 mac; I did create the .env file and added that line, as explained in the installation instructions.

**Comment by simjanos-dev** [comment]
Were you trying to update, or is this your first install? If you used it before, what linguacafe version did you use?

@sergiolaverde0 Do you have any idea? 

It's really strange, especially because it says that the MySQL has an error, not the Python server.

**Comment by SunflowerFuture** [comment]
it's a first install.

**Comment by sergiolaverde0** [comment]
Hi, please try running this command: `docker compose pull` and check if you get the same error message.

If you do, please run the command `docker image ls` and paste the output here. If you otherwise don't get any error run `docker compose up -d` to have linguacafe working normally in your system.

**Comment by SunflowerFuture** [comment]
pull gave the same error; image ls just gives:
REPOSITORY   TAG       IMAGE ID   CREATED   SIZE

Nothing else...

**Comment by sergiolaverde0** [comment]
I think I know what is causing this, but I'm not entirely sure why it is only affecting you. For now open the file `docker-compose.yml` with a text editor and edit the mysql section to add a line at the end of it, like this:

```
 mysql:
        image: mysql:8.0
        container_name: linguacafe-database
        restart: unless-stopped
        tty: true
        volumes:
            - ./database:/var/lib/mysql
        environment:
            MYSQL_DATABASE: ${DB_DATABASE:-linguacafe}
            MYSQL_USER: ${DB_USERNAME:-linguacafe}
            MYSQL_PASSWORD: ${DB_PASSWORD:-linguacafe}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-linguacafe}
            SERVICE_NAME: linguacafe
        command: mysqld --general-log=1 --general-log-file=/var/lib/mysql/general-log.log
        networks:
            - linguacafe
        platform: ${PLATFORM:-}
```

Tomorrow I will talk with simjanos on ho to address this.
