### ISSUE TITLE
Please add external MySQL support

### ISSUE THREAD

**Issue by xXAzazelXx** [simjanos-dev/LinguaCafe#266]
Hey !

Is it please possible to add support for var to point to external MySQL??

similar to this:

DB_DATABASE="linguacafe"
DB_USERNAME="linguacafe"
DB_PASSWORD="linguacafe"

eg DB_HOST=

**Comment by simjanos-dev** [comment]
Sure, it can be added. Actually, you can add it yourself in the meantime I think. 

You can modify the `docker-compose.yml` if you are using v0.12:
```
    webserver:
        image: ghcr.io/simjanos-dev/linguacafe-webserver:${VERSION:-latest}
        container_name: linguacafe-webserver
        restart: unless-stopped
        depends_on:
            - mysql
        volumes:
            - ./storage:/var/www/html/storage
        environment:
            DB_DATABASE: ${DB_DATABASE:-linguacafe}
            DB_USERNAME: ${DB_USERNAME:-linguacafe}
            DB_PASSWORD: ${DB_PASSWORD:-linguacafe}
            DB_HOST: ${DB_HOST:-linguacafe-database}
            DB_PORT: ${DB_PORT:-3306}
```

Then add these variables to a .env file.

At startup it will create the necessary tables, but you will have to create the database itself before that.
