### ISSUE TITLE
Problems setting up docker on synology NAS. Apache AH00072

### ISSUE THREAD

**Issue by unickq** [simjanos-dev/LinguaCafe#364]
Hey there,

I'm trying to launch your app on my NAS and facing with apache issues.
It's a Synology 218+ nas with the latest DSM 8, which has docker 24 and 2Core Intel Celeron J3355 and 10gb ram

```bash
2024/10/09 01:20:04 | stderr | AH00015: Unable to open logs
2024/10/09 01:20:04 | stderr | no listening sockets available, shutting down
2024/10/09 01:20:04 | stderr | (13)Permission denied: AH00072: make_sock: could not bind to address 0.0.0.0:80
2024/10/09 01:20:04 | stderr | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 192.168.48.2. Set the 'ServerName' directive globally to suppress this message
2024/10/09 01:20:03 | stdout | Database seeding completed successfully.
2024/10/09 01:20:03 | stdout | Seeded:  Database\Seeders\FontTypeSeeder (4.33ms)
2024/10/09 01:20:03 | stdout | Seeding: Database\Seeders\FontTypeSeeder
2024/10/09 01:20:03 | stdout | Seeded:  Database\Seeders\DictionarySeeder (1.52ms)
2024/10/09 01:20:03 | stdout | Seeding: Database\Seeders\DictionarySeeder
2024/10/09 01:20:03 | stdout | Seeded:  Database\Seeders\SettingsSeeder (38.33ms)
2024/10/09 01:20:03 | stdout | Seeding: Database\Seeders\SettingsSeeder
2024/10/09 01:20:03 | stdout | Nothing to migrate.
2024/10/09 01:20:03 | stdout | Folder already exists: ./storage/logs
2024/10/09 01:20:03 | stdout | Folder already exists: ./storage/framework/views
2024/10/09 01:20:03 | stdout | Folder already exists: ./storage/framework/testing
2024/10/09 01:20:03 | stdout | Folder already exists: ./storage/framework/sessions
2024/10/09 01:20:03 | stdout | Folder already exists: ./storage/framework/cache/data
2024/10/09 01:20:03 | stdout | Folder already exists: ./storage/app/temp/dictionaries
2024/10/09 01:20:03 | stdout | Folder already exists: ./storage/app/public
2024/10/09 01:20:03 | stdout | Folder already exists: ./storage/app/images/book_images
2024/10/09 01:20:03 | stdout | Folder already exists: ./storage/app/fonts
2024/10/09 01:20:03 | stdout | Folder already exists: ./storage/app/dictionaries
```

Config for YML - latest prod - https://github.com/simjanos-dev/LinguaCafe/blob/main/docker-compose.yml

.env:
```.env
DB_ROOT_PASSWORD=rootpwd
```
When I start without .env - MySQL doesn't start - `container for service mysql is unhealthy`

From what I found, it doesn't seem like **80** port. From [this](https://askubuntu.com/questions/338218/why-am-i-getting-permission-denied-make-sock-could-not-bind-to-address-when) I found that I need to edit `/etc/apache2/ports.conf`.
But I can't, your [dockerfile](https://github.com/simjanos-dev/LinguaCafe/blob/main/docker/PhpDockerfile#L10) is built with `--no-install-recommends` and seems like doesn't have any text editor for `Debian GNU/Linux 12 (bookworm)`.

I can't install anything because no root access and sudo is not available. And setting it up with `su -` doesn't work because of `adduser --ingroup laravel --disabled-password` in dockerfile.

Container crashes immediately, but when stud down DB container - I'm able to log in and
```bash
laravel@b814c2f89607:/var/www/html$ service apache2 status                       
apache2 is not running ... failed!                                               
laravel@b814c2f89607:/var/www/html$ service apache2 start                        
Starting Apache httpd web server: apache2AH00558: apache2: Could not reliably det
ermine the server's fully qualified domain name, using 192.168.48.2. Set the 'Ser
verName' directive globally to suppress this message                             
(13)Permission denied: AH00072: make_sock: could not bind to address 0.0.0.0:80  
no listening sockets available, shutting down                                    
AH00015: Unable to open logs                                                     
Action 'start' failed.                                                           
The Apache error log may have more information.                                  
.                                                     
```

```
When the http daemon starts, it tries to bind the 80 port, which is a port within the system assigned ports and as such it can only be accessed by root. 
In order to be able to run it as a non-root user you could change the port to a non-reserved one (higher than 1024), or use an account with enough privileges.
```

But I don't know how to debug it for now - I need to build it myself, using my own docker cloud, and then PR with port up.

However, everything is working on my Mac 😿

**Comment by unickq** [comment]
omg, after 4 hours of debugging

`user: root` added to main app worked

```yml
services:
  webserver:
    image: ghcr.io/simjanos-dev/linguacafe-webserver:${VERSION:-latest}
    user: root
```

**Comment by unickq** [comment]
omg, after 4 hours of debugging

`user: root` added to main app worked

```yml
services:
  webserver:
    image: ghcr.io/simjanos-dev/linguacafe-webserver:${VERSION:-latest}
    user: root
```

**Comment by unickq** [comment]
omg, after 4 hours of debugging

`user: root` added to main app worked

```yml
services:
  webserver:
    image: ghcr.io/simjanos-dev/linguacafe-webserver:${VERSION:-latest}
    user: root
```

**Comment by simjanos-dev** [comment]
Hi!

Im not sure why it does not work on your nas. 

I think using root as a user will cause other permission problems, for example when trying to import a book.

**Comment by elmpp** [comment]
4 hour problem for me also. Root user doesn't cut the mustard.

Needed to avoid the synology root escalation problems by remapping port 80 to 8080 in apache:

---

Ah, the classic Synology "kernel too old" wall.

That error confirms exactly what we are up against: Synology runs notoriously outdated Linux kernels on its NAS units (often version 3.10 or 4.4). The ip_unprivileged_port_start feature wasn't introduced until Linux kernel 4.11, which is why that file literally does not exist on your system.

Since we cannot alter the NAS kernel, and we cannot force Apache to hold onto root privileges inside this specific image, we have to stop fighting the system.

Instead of trying to force the container to bind to a restricted port (80), we are going to tell Apache to listen on port 8080 internally. This completely bypasses Synology's security restrictions, allowing you to run the container cleanly as your regular NAS user (1028:65536) without any special permissions.

Here is the foolproof workaround.

## Step 1: Create Custom Apache Config Files on your NAS
We need to feed Apache configuration files that tell it to use the new port.

SSH into your NAS (or use File Station) and create a new folder called apache-config inside your LinguaCafe directory:
/volume2/docker/lingua-cafe/apache-config/

Inside that new folder, create a file named ports.conf and paste this exactly:

```Apache
Listen 8080
```

In that same folder, create a second file named 000-default.conf and paste this standard Laravel virtual host configuration:

```Apache
<VirtualHost *:8080>
    ServerAdmin webmaster@localhost
    DocumentRoot /var/www/html/public

    <Directory /var/www/html/public>
        AllowOverride All
        Require all granted
    </Directory>

    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
```

## Step 2: Update Your docker-compose.yml
Now we clean up the file. We can rip out all the previous workarounds (cap_add, privileged, and sysctls) because port 8080 doesn't require any of them.

Update your webserver service to look like this:

```YAML
    webserver:
        image: ghcr.io/simjanos-dev/linguacafe-webserver:${VERSION:-latest}
        container_name: linguacafe-webserver
        restart: on-failure:2
        
        depends_on:
            mysql:
                condition: service_healthy
        volumes:
            - /volume2/docker/lingua-cafe/storage:/var/www/html/storage
            
            # Map the two new Apache files we just created
            - /volume2/docker/lingua-cafe/apache-config/ports.conf:/etc/apache2/ports.conf
            - /volume2/docker/lingua-cafe/apache-config/000-default.conf:/etc/apache2/sites-available/000-default.conf
            
            # Internal volumes for the supervisor configs
            - supervisor-horizon:/etc/supervisor/conf.d/horizon.conf
            - supervisor-websockets:/etc/supervisor/conf.d/websockets.conf
        environment:
            # (Keep all your existing environment variables exactly the same here)
            DB_DATABASE: ${DB_DATABASE:-linguacafe}
            DB_USERNAME: ${DB_USERNAME:-linguacafe}
            DB_PASSWORD: ${DB_PASSWORD:-linguacafe}
            DB_HOST: ${DB_HOST:-linguacafe-database}
            DB_PORT: ${DB_PORT:-3306}
            BACKUP_INTERVAL: "59 23 * * *"
            MAX_SAVED_BACKUPS: 14
            TZ: Europe/Amsterdam
        healthcheck:
            # Update the healthcheck to ping the new 8080 port
            test: ["CMD", "curl", "-f", "http://localhost:8080"]
            interval: 20s
            timeout: 10s
            retries: 3
            start_period: 20s
        ports:
            - "6001:6001"
            # Map your host port 9191 to the new internal 8080 port
            - "${PORT:-9191}:8080"
        networks:
            - linguacafe
        extra_hosts:
            - "host.docker.internal:host-gateway"
```
