### ISSUE TITLE
Use github ghcr.io for Docker images 

### ISSUE THREAD

**Issue by systemcrash** [simjanos-dev/LinguaCafe#48]
There are a few pages which document this. Keeping everything on github is really clean and easy. Not everyone is aware github has this feature.

Here is an example Github workflow that could be used as a template: https://github.com/porjo/ytdl-web/blob/master/.github/workflows/build-and-push.yml . The only thing that should need changing is to replace:

```yaml
on:
  push:
    tags:
      - "*"
```
with

```yaml
on:
  release:
    types: [created]
```

The repository owner would first need to create a PAT with permissions `repo, workflow, write:packages` and add it to the repository's secrets.
