### ISSUE TITLE
Database ENV Variables + other DB types integration

### ISSUE THREAD

**Issue by shyonae** [simjanos-dev/LinguaCafe#86]
Hi, stumbled onto this project from Reddit and I'm impressed, but while reading the README I couldn't help but notice this line:

- `Do not modify the mysql username, password and database name.`

Would it be possible to have some environment variables so those can be customized?

Also something else, it would be great to have support for other database types like Postgres.

**Comment by simjanos-dev** [comment]
Hi!

Yes, I started thinking about it when I found people who changed it. Right before v0.5 I've found 2 people who tried to change it, so there are probably more, so I've added it to the readme. I'll look into how to do it in the future. 

I think the MySQL port is only open because I used it for development. Would the default password still be a problem if I removed that? It would still be accessible through docker commands from the host machine.

I don't think I'll change database. Laravel does support it, so maybe if it is a popular request, and everything else is finished with LinguaCafe. But I want to prioritize other things first.

**Comment by simjanos-dev** [comment]
Nevermind,  I think I'll just mount the Laravel .env file as well, so people can change it. I will add it to the next update.

**Comment by sergiolaverde0** [comment]
You can rawdog the `docker-compose.yml` to pass them and it apparently does work, you have to use the variables used by [this file](https://github.com/simjanos-dev/LinguaCafe/blob/0b5083a8662a04d69069eb47c997e265dc740bd1/config/database.php#L46), like this:

```
services:
    webserver:
        image: ghcr.io/simjanos-dev/linguacafe-webserver:main
        container_name: linguacafe-webserver
        depends_on:
            - mysql
        volumes:
            - ./storage:/var/www/html/storage
        environment:
            DB_DATABASE: myexampledatabase
            DB_USERNAME: myexampleuser
            DB_PASSWORD: myexamplepassword
        ports:
            - "9191:80"
            - "3000:3000"
        networks:
            - linguacafe
        extra_hosts:
            - "host.docker.internal:host-gateway"
    mysql:
        image: mysql:8.0
        container_name: linguacafe-database
        restart: unless-stopped
        tty: true
        ports:
            - "3308:3306"
        volumes:
            - ./database:/var/lib/mysql
        environment:
            MYSQL_DATABASE: myexampledatabase
            MYSQL_USER: myexampleuser
            MYSQL_PASSWORD: myexamplepassword
            MYSQL_ROOT_PASSWORD: mysupersecurerootpassword
            SERVICE_NAME: linguacafe
        command: mysqld --general-log=1 --general-log-file=/var/lib/mysql/general-log.log
        networks:
            - linguacafe
```

I'm currently testing if this can be actually relied on without breaking anything.

**Comment by sergiolaverde0** [comment]
I think this is working fine:
```
docker-compose.yml
services:
    webserver:
        image: ghcr.io/simjanos-dev/linguacafe-webserver:main
        container_name: linguacafe-webserver
        depends_on:
            - mysql
        volumes:
            - ./storage:/var/www/html/storage
        environment:
            DB_DATABASE: ${DB_NAME}
            DB_USERNAME: ${DB_USER}
            DB_PASSWORD: ${DB_PASSWORD}
        ports:
            - "9191:80"
            - "3000:3000"
        networks:
            - linguacafe
        extra_hosts:
            - "host.docker.internal:host-gateway"
    mysql:
        image: mysql:8.0
        container_name: linguacafe-database
        restart: unless-stopped
        tty: true
        ports:
            - "3308:3306"
        volumes:
            - ./database:/var/lib/mysql
        environment:
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            SERVICE_NAME: linguacafe
        command: mysqld --general-log=1 --general-log-file=/var/lib/mysql/general-log.log
        networks:
            - linguacafe
    python:
        container_name: linguacafe-python-service
        command: /app/manage.py runserver 0.0.0.0:8678
        restart: unless-stopped
        tty: true
        image: ghcr.io/simjanos-dev/linguacafe-python-service:main
        volumes:
            - ./storage:/var/www/html/storage
        networks:
            - linguacafe
        # platform: linux/amd64
```
```
.env
DB_NAME=myexampledatabase
DB_PASSWORD=myexamplepassword
DB_USER=myexampleuser
DB_ROOT_PASSWORD=mysupersecurerootpassword
```

What is left to decide is what else users should (and shouldn't) be able to easily modify.
